name: npm-setup
description: "Simple action to build a docker image and push it to repository"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      id: npm-cache
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org/'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts
