name: NPM setup
description: "Simple action to get the nodejs and NPM enviroment"
inputs:
  NPM_TOKEN:
    description: 'NPM access token'
    required: true
  SRC_FOLDER:
    description: 'Source folder of the package'
    default: '.'
    type: 'string'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      id: npm-cache
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org/'
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          ./node_modules
          ./exposed_src
          ./target
        key: modules-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      env:
        FOLDER: ${{ inputs.SRC_FOLDER }}
      run: cd $FOLDER && npm ci --ignore-scripts
    - env:
        FOLDER: ${{ inputs.SRC_FOLDER }}
      # run: npm run build # TODO
      run: cd $FOLDER && npm run build:lib && npm run build:sdk
