name: NPM setup
description: "Simple action to get the nodejs and NPM enviroment"
inputs:
  NPM_TOKEN:
    description: 'NPM access token'
    required: true
  FOLDER:
    description: 'Move to correct location'
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - shell: sh
      run: cd ${{ inputs.FOLDER }}
    - uses: actions/setup-node@v2
      id: npm-cache
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org/'
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      shell: sh
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts
    - shell: sh
      run: npm run build:lib
