name: NPM publish
description: "Simple action to publish package on NPM"
inputs:
  RELEASE_VERSION:
    description: 'Version to release'
    required: true
  RELEASE_TYPE:
    description: 'Type of release'
    required: true
  SRC_FOLDER:
    description: 'Source folder of the package'
    default: '.'
    type: 'string'

runs:
  using: composite
  steps:
    - shell: sh
      env:
        VERSION: ${{ inputs.RELEASE_VERSION }}
        FOLDER: ${{ inputs.SRC_FOLDER }}
      run: cd $FOLDER && npm version --no-git-tag-version --allow-same-version $VERSION
    - if: ${{ inputs.RELEASE_TYPE == 'release' }}
      env:
        FOLDER: ${{ inputs.SRC_FOLDER }}
      shell: sh
      run: cd $FOLDER && npm version && echo "Release" && ls -la
    - if: ${{ inputs.RELEASE_TYPE == 'prerelease' }}
      env:
        FOLDER: ${{ inputs.SRC_FOLDER }}
      shell: sh
      run: cd $FOLDER && npm version && echo "Prerelease" && ls -la
