name: NPM publish
description: "Simple action to publish package on NPM"
inputs:
  RELEASE_VERSION:
    description: 'Version to release'
    required: true
  RELEASE_TYPE:
    description: 'Type of release'
    required: true
  SRC_FOLDER:
    description: 'Source folder of the package'
    default: '.'
    type: 'string'

runs:
  using: composite
  steps:
    - shell: sh
      env:
        SRC_FOLDER: ${{ inputs.SRC_FOLDER }}
      run: cd $SRC_FOLDER
    - shell: sh
      env:
        VERSION: ${{ inputs.RELEASE_VERSION }}
      run: npm version --no-git-tag-version --allow-same-version $VERSION
    - if: ${{ inputs.RELEASE_TYPE == 'release' }}
      shell: sh
      run: npm publish
    - if: ${{ inputs.RELEASE_TYPE == 'prerelease' }}
      shell: sh
      run: npm publish --tag alpha
