name: NPM publish
description: "Simple action to publish package on NPM"
inputs:
  NPM_TOKEN:
    description: 'NPM access token'
    required: true
  RELEASE_VERSION:
    description: 'Version to release'
    required: true
  RELEASE_TYPE:
    description: 'Type of release'
    required: true

runs:
  using: composite
  steps:
    - shell: sh
      env:
        VERSION: ${{ inputs.RELEASE_VERSION }}
      run: npm version --no-git-tag-version --allow-same-version $VERSION
    - if: ${{ RELEASE_TYPE == 'release' }}
      shell: sh
      run: npm publish
    - if: ${{ RELEASE_TYPE == 'prerelease' }}
      shell: sh
      run: npm publish --tag alpha
