name: npm-cache
description: "Simple action to get the node cache"
inputs:
  npm-token:
    description: 'NPM access token'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      id: npm-cache
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org/'
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}