name: 'get-event-information'
description: 'Generating information used to create and publish images'
outputs:
  group:
    description: 'Group name of the image'
  name:
    description: 'Name of the image'
  image-name:
    description: 'Full name of the image used for uploading to image registry'
  tag-name:
    description: 'Tag name/version of the image'
  namespace:
    description: 'Namespace of the image'
  release-type:
    description: 'Release or prerelease?'
  env-name:
    description: 'Environment name'
runs:
  using: 'node16'
  main: 'dist/index.js'
